name: Main
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2]
        rails: ['7.0', '7.1']
        include:
          - ruby: 3.2
            rails: '7.0'

    name: Ruby ${{ matrix.ruby }} - Rails ${{ matrix.rails }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
